# Generated by Django 5.1.6 on 2025-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_todo_priority_todo_end_time_todo_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='notify_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='repeat_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='repeat_frequency',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='repeat_type',
            field=models.CharField(choices=[('N', "Don't repeat"), ('W', 'Every X weeks'), ('M', 'Every X months'), ('Y', 'Every X years')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_type',
            field=models.CharField(choices=[('TODO', 'TODO'), ('CLASS', 'CLASS'), ('EVENT', 'EVENT')], default='TODO', max_length=5),
        ),
    ]
