# Generated by Django 5.1.6 on 2025-02-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_todo_delivered_todo_notify_time_todo_repeat_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='repeat_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='repeat_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
